# Generated by Django 2.1.5 on 2019-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0002_auto_20190504_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestatistics',
            name='visits',
            field=models.IntegerField(),
        ),
    ]
