# Generated by Django 2.1.5 on 2019-05-04 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garbeco', '0004_auto_20190504_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lgt', models.FloatField()),
                ('types', models.CharField(choices=[('normal', 'normal'), ('paper', 'paper'), ('glass', 'glass'), ('plastic', 'plastic')], default='normal', max_length=15)),
                ('description', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
