# Generated by Django 2.1.5 on 2019-05-04 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0005_garbagebin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagebin',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
