# Generated by Django 2.1.5 on 2019-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0006_auto_20190504_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagebin',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
