# Generated by Django 2.1.5 on 2019-05-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0008_auto_20190505_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GarbageTypes',
            new_name='GarbageType',
        ),
    ]
