# Generated by Django 2.1.5 on 2019-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0009_auto_20190505_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagetype',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
