# Generated by Django 2.1.5 on 2019-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0010_auto_20190505_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagetype',
            name='name',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
