# Generated by Django 2.1.5 on 2019-05-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0012_auto_20190505_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagetype',
            name='icon',
        ),
        migrations.AddField(
            model_name='garbagetype',
            name='icon_path',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
