# Generated by Django 2.1.5 on 2019-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0013_auto_20190505_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagebin',
            name='types',
        ),
        migrations.AddField(
            model_name='garbagebin',
            name='types',
            field=models.ManyToManyField(to='garbeco.GarbageType'),
        ),
    ]
