# Generated by Django 2.1.5 on 2019-05-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0014_auto_20190505_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbagebin',
            old_name='lgt',
            new_name='lng',
        ),
    ]
