# Generated by Django 2.1.5 on 2019-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0017_auto_20190506_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='like',
            name='belongs_to_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='belongs_to_type',
            field=models.CharField(choices=[('garbin', 'garbage bin'), ('event', 'event')], default='garbin', max_length=20),
            preserve_default=False,
        ),
    ]
