# Generated by Django 2.1.5 on 2019-05-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbeco', '0018_auto_20190506_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='garbin',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
